//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatilSeyahatSitesiMvc5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mvc5TatilSeyehatEntities : DbContext
    {
        public Mvc5TatilSeyehatEntities()
            : base("name=Mvc5TatilSeyehatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLADMIN> TBLADMIN { get; set; }
        public virtual DbSet<TBLADRES> TBLADRES { get; set; }
        public virtual DbSet<TBLBLOG> TBLBLOG { get; set; }
        public virtual DbSet<TBLILETISIM> TBLILETISIM { get; set; }
        public virtual DbSet<TBLYORUMLAR> TBLYORUMLAR { get; set; }
        public virtual DbSet<TBLACIKLAMA> TBLACIKLAMA { get; set; }
        public virtual DbSet<TBLMUZELER> TBLMUZELER { get; set; }
        public virtual DbSet<TBLMUZEYORUM> TBLMUZEYORUM { get; set; }
        public virtual DbSet<TBLOTELLER> TBLOTELLER { get; set; }
        public virtual DbSet<TBLOTELYORUM> TBLOTELYORUM { get; set; }
        public virtual DbSet<TBLRESTAURANT> TBLRESTAURANT { get; set; }
        public virtual DbSet<TBLRESTAURANTYORUM> TBLRESTAURANTYORUM { get; set; }
    }
}
